name: Block Labels

on:
  issues:
    types: [labeled, unlabeled]
  pull_request:
    types: [labeled, unlabeled]

jobs:
  block-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check for blocked labels
        uses: actions/github-script@v7
        with:
          script: |
            const blockedLabels = [
              'wontfix',
              'invalid',
              'duplicate',
              'help wanted',
              'good first issue'
            ];
            
            const eventLabel = context.payload.label?.name;
            const action = context.payload.action;
            
            if (action === 'labeled' && blockedLabels.includes(eventLabel)) {
              core.setFailed(`Label "${eventLabel}" is not allowed. Please remove it.`);
            } 